fixtures:
#  repositories:
#    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
#    concat: "git://github.com/puppetlabs/puppetlabs-concat.git"
  symlinks:
    apache: "#{source_dir}"
    stdlib: "#{source_dir}/../stdlib"
    concat: "#{source_dir}/../concat"
