---
".gitlab-ci.yml":
  delete: true
".rubocop.yml":
  default_configs:
    inherit_from: ".rubocop_todo.yml"
".travis.yml":
  global_env: 
    - HONEYCOMB_WRITEKEY="7f3c63a70eecc61d635917de46bea4e6",HONEYCOMB_DATASET="litmus tests"
  deploy_to_forge:
    enabled: false
  use_litmus: true
  litmus:
    provision_list:
      - travis_ub
      - travis_deb
      - travis_el7
  secure: ''
  branches:
  - release
  simplecov: true
  notifications:
    slack:
      secure: MrXQwGIUO7WNmLbe7iiWgURiZPUgyvDLkKe3d9S58ohE6gdN6pqlsjP8YgodK8JmIBV1zp5Wj/0cXUmY3xvCtnDmII0DCEk2Y1Cs/W1drKZtS/0BsUpJkj0rDP2fSlKsY5ifESdEta/y8+NkjRnqadbl7SQPYeek4IjAfxjjuig=
appveyor.yml:
  delete: true
Gemfile:
  optional:
    ":development":
    - gem: github_changelog_generator
      git: https://github.com/skywinder/github-changelog-generator
      ref: 20ee04ba1234e9e83eb2ffb5056e23d641c7a018
      condition: Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')
Rakefile:
  requires:
  - puppet-lint/tasks/puppet-lint
spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
