---
".gitlab-ci.yml":
  delete: true
".rubocop.yml":
  include_todos: true
appveyor.yml:
  delete: true

Gemfile:
  optional:
    ":development":
    - gem: github_changelog_generator
spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
.gitpod.Dockerfile:
  unmanaged: false
.gitpod.yml:
  unmanaged: false
.github/workflows/nightly.yml:
  unmanaged: false
.github/workflows/pr_test.yml:
  unmanaged: false
.github/workflows/auto_release.yml:
  unmanaged: false
Rakefile:
  changelog_max_issues: 500
  extras:
    "FastGettext.default_text_domain = 'default-text-domain'"
.github/workflows/spec.yml:
  checks: 'syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop'
  unmanaged: false
.github/workflows/release.yml:
  unmanaged: false
.travis.yml:
  delete: true
changelog_since_tag: "3.2.0"
