---
".gitlab-ci.yml":
  delete: true
".rubocop.yml":
  include_todos: true
appveyor.yml:
  delete: true

spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
.gitpod.Dockerfile:
  unmanaged: false
.gitpod.yml:
  unmanaged: false
.github/workflows/auto_release.yml:
  unmanaged: false
.github/workflows/ci.yml:
  unmanaged: true
.github/workflows/nightly.yml:
  unmanaged: true
.github/workflows/release.yml:
  unmanaged: false
Rakefile:
  changelog_max_issues: 500
  extras:
    "FastGettext.default_text_domain = 'default-text-domain'"
.travis.yml:
  delete: true
changelog_since_tag: "3.2.0"
Rakefile:
  extra_disabled_lint_checks:
    - anchor_resource
    - 140chars
