class apache::mod::default {
  apache::mod { 'actions': }
  apache::mod { 'alias': }
  apache::mod { 'auth_basic': }
  apache::mod { 'auth_digest': }
  apache::mod { 'authn_alias': }
  apache::mod { 'authn_anon': }
  apache::mod { 'authn_dbm': }
  apache::mod { 'authn_default': }
  apache::mod { 'authn_file': }
  apache::mod { 'authnz_ldap': }
  apache::mod { 'authz_dbm': }
  apache::mod { 'authz_default': }
  apache::mod { 'authz_groupfile': }
  apache::mod { 'authz_host': }
  apache::mod { 'authz_owner': }
  apache::mod { 'authz_user': }
  apache::mod { 'autoindex': }
  apache::mod { 'cache': }
  apache::mod { 'cgi': }
  apache::mod { 'dav': }
  apache::mod { 'dav_fs': }
  apache::mod { 'deflate': }
  apache::mod { 'dir': }
  apache::mod { 'disk_cache': }
  apache::mod { 'env': }
  apache::mod { 'expires': }
  apache::mod { 'ext_filter': }
  apache::mod { 'file_cache': }
  apache::mod { 'headers': }
  apache::mod { 'include': }
  apache::mod { 'info': }
  apache::mod { 'ldap': }
  apache::mod { 'log_config': }
  apache::mod { 'logio': }
  apache::mod { 'mem_cache': }
  apache::mod { 'mime': }
  apache::mod { 'mime_magic': }
  apache::mod { 'negotiation': }
  apache::mod { 'proxy': }
  apache::mod { 'proxy_balancer': }
  apache::mod { 'proxy_connect': }
  apache::mod { 'proxy_ftp': }
  apache::mod { 'proxy_http': }
  apache::mod { 'rewrite': }
  apache::mod { 'setenvif': }
  apache::mod { 'speling': }
  apache::mod { 'status': }
  apache::mod { 'suexec': }
  apache::mod { 'usertrack': }
  apache::mod { 'version': }
  apache::mod { 'vhost_alias': }
}
