name: "ci"

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:
    
jobs:
  Spec:
    uses: "puppetlabs/cat-github-actions/.github/workflows/module_ci.yml@Adding-BUNDLE_WITHOUT-in-release-prep"
    with:
      runs_on: "ubuntu-20.04"
    secrets: "inherit"

  Acceptance:
    needs: Spec
    uses: "puppetlabs/cat-github-actions/.github/workflows/module_acceptance.yml@Adding-BUNDLE_WITHOUT-in-release-prep"
    with:
      runs_on: "ubuntu-20.04"
    secrets: "inherit"
